:experimental:
:commandkey: &#8984;
:toc: macro
:source-highlighter: highlight.js

= How to Create Your Own Test Site for Passkeys using `java-webauthn-server`

Below is a step-by-step guide on setting up a test site to experiment with passkeys. This will involve cloning a repository, running a Gradle wrapper, and configuring ngrok.com.


**Prerequisite**:

- https://adoptium.net/[Java 17] - If needed, I recommend using https://sdkman.io/[SDKMAN!] to manage and install multiple versions of Java.

toc::[]

== Installing Java 17

This project requires Java 17. If you don't have Java 17 installed, I recommend using https://sdkman.io/[SDKMAN!] to  install multiple versions of Java.

NOTE: Java 20 is not supported for this guide.

[source,shell]
----
java -version
----


== Clone the Git Repository


Open a terminal or command prompt.

Navigate to the directory where you want to clone the repository.

Run the following command:

[source,shell]
----
git clone https://github.com/marcofanti/java-webauthn-server.git passkeys-playground
----


Once the cloning is done, navigate to the cloned directory:

[source,shell]
----
cd passkeys-playground
----

=== Run the Gradle Wrapper

To run the Gradle wrapper, execute the following command for UNIX-like systems:

[source, shell]
----
./gradlew :webauthn-server-demo:run
----
or for Windows:

[source, shell]
----
gradlew.bat :webauthn-server-demo:run
----

=== Open a browser and navigate to https://localhost:8443

To run a Chrome browser on a Mac, open a terminal and run:

[source, shell]
----
open -a "Google Chrome" https://localhost:8443
----

=== Test creating a new account with passkey

Enter a username and press the "Create account with passkey" button.

Press the "Log out" button.

Press the "Authenticate with passkey" button and verify that you can login with the passkey you just created.

=== Press ctrl-c to stop the server

== Testing with ngrok

=== Sign up for ngrok.com

Visit [https://dashboard.ngrok.com/signup](https://dashboard.ngrok.com/signup) and sign up for a free account.

Copy your authtoken from the ngrok dashboard [https://dashboard.ngrok.com/get-started/your-authtoken](https://dashboard.ngrok.com/get-started/your-authtoken).

Open a terminal and authenticate your ngrok agent. You only have to do this once. The Authtoken is saved in the default configuration file.

[source, shell]
----
ngrok config add-authtoken a364fYAU71ZyTTFtRv2Ki5DBrMoEBu_defdBdgPj
----

=== Configure ngrok.com endpoint


Go to [https://dashboard.ngrok.com/cloud-edge/endpoints] and create a new endpoint. Copy the URL of the endpoint.

[source, shell]
----
ngrok http https://localhost:8443 --domain=your-own-domain.ngrok-free.app
----

=== Run the Gradle Wrapper

To run the Gradle wrapper, execute the following command for UNIX-like systems, specifying the ngrok endpoint URL and the ngrok domain you created in the previous step:

[source, shell]
----

./gradlew --no-daemon :webauthn-server-demo:run -D YUBICO_WEBAUTHN_ALLOWED_ORIGINS=https://ship-boat-building.ngrok-free.app.ngrok-free.app -D YUBICO_WEBAUTHN_RP_ID=your-own-domain.ngrok-free.app.ngrok-free.app
----

=== Open a browser and navigate to https://your-own-domain.ngrok-free.app:8443

=== Test creating a new account with passkey

Enter a username and press the "Create account with passkey" button.

Press the "Log out" button.

Press the "Authenticate with passkey" button and verify that you can login with the passkey you just created.

=== Press ctrl-c to stop the server

=== Press ctrl-c to stop ngrok endpoint



With these steps completed, you should have a working test site to try out passkeys. Remember to consult the official documentation of each tool for detailed configuration options and further reading.